import jsPDF from "jspdf";
import { format } from "date-fns";
import { Application } from "@/types";

const BRAND_BLUE: [number, number, number] = [27, 59, 111]; // #1B3B6F
const ACCENT_TEAL: [number, number, number] = [31, 182, 166]; // #1FB6A6
const TEXT_DARK: [number, number, number] = [33, 37, 41];
const TEXT_MUTED: [number, number, number] = [108, 117, 125];
const LINE_LIGHT: [number, number, number] = [224, 228, 234];

const MARGIN_X = 18;
const PAGE_WIDTH = 210; // A4 mm
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN_X * 2;

interface Cursor {
  y: number;
}

const setText = (pdf: jsPDF, color: [number, number, number], size: number, style: "normal" | "bold" = "normal") => {
  pdf.setTextColor(color[0], color[1], color[2]);
  pdf.setFontSize(size);
  pdf.setFont("helvetica", style);
};

const buildHeader = (pdf: jsPDF, application: Application, cursor: Cursor) => {
  // Brand bar
  pdf.setFillColor(BRAND_BLUE[0], BRAND_BLUE[1], BRAND_BLUE[2]);
  pdf.rect(0, 0, PAGE_WIDTH, 26, "F");

  setText(pdf, [255, 255, 255], 18, "bold");
  pdf.text("ThaiDriveSecure", MARGIN_X, 13);

  setText(pdf, [255, 255, 255], 9, "normal");
  pdf.text("Cross-Border Vehicle Insurance Document", MARGIN_X, 19);

  // Right-side meta
  setText(pdf, [255, 255, 255], 9, "normal");
  const generatedAt = format(new Date(), "dd MMM yyyy, HH:mm");
  pdf.text(`Generated: ${generatedAt}`, PAGE_WIDTH - MARGIN_X, 13, { align: "right" });
  pdf.text(`Order ID: ${application.orderId || application.id}`, PAGE_WIDTH - MARGIN_X, 19, { align: "right" });

  // Accent strip
  pdf.setFillColor(ACCENT_TEAL[0], ACCENT_TEAL[1], ACCENT_TEAL[2]);
  pdf.rect(0, 26, PAGE_WIDTH, 1.5, "F");

  cursor.y = 38;
};

const sectionTitle = (pdf: jsPDF, title: string, cursor: Cursor) => {
  setText(pdf, BRAND_BLUE, 11, "bold");
  pdf.text(title.toUpperCase(), MARGIN_X, cursor.y);
  cursor.y += 2;
  pdf.setDrawColor(LINE_LIGHT[0], LINE_LIGHT[1], LINE_LIGHT[2]);
  pdf.setLineWidth(0.3);
  pdf.line(MARGIN_X, cursor.y, MARGIN_X + CONTENT_WIDTH, cursor.y);
  cursor.y += 6;
};

const row = (pdf: jsPDF, label: string, value: string, cursor: Cursor) => {
  setText(pdf, TEXT_MUTED, 9, "normal");
  pdf.text(label, MARGIN_X, cursor.y);
  setText(pdf, TEXT_DARK, 10, "normal");
  const lines = pdf.splitTextToSize(value || "-", CONTENT_WIDTH - 55);
  pdf.text(lines, MARGIN_X + 55, cursor.y);
  cursor.y += Math.max(6, lines.length * 5);
};

const buildCustomerSection = (pdf: jsPDF, application: Application, cursor: Cursor) => {
  sectionTitle(pdf, "Customer Information", cursor);
  row(pdf, "Full Name", application.name, cursor);
  row(pdf, "Phone", application.phone, cursor);
  if (application.email) row(pdf, "Email", application.email, cursor);
  row(pdf, "Passengers", String(application.passengers ?? 1), cursor);
  cursor.y += 4;
};

const buildVehicleSection = (pdf: jsPDF, application: Application, cursor: Cursor) => {
  sectionTitle(pdf, "Vehicle Details", cursor);
  row(pdf, "Vehicle Type", application.vehicleType, cursor);
  row(pdf, "Border Route", application.where, cursor);
  cursor.y += 4;
};

const buildTravelSection = (pdf: jsPDF, application: Application, cursor: Cursor) => {
  sectionTitle(pdf, "Travel Period", cursor);
  const depart = application.travel?.departDate ? format(application.travel.departDate, "dd MMM yyyy") : "-";
  const ret = application.travel?.returnDate ? format(application.travel.returnDate, "dd MMM yyyy") : "-";
  row(pdf, "Depart Date", depart, cursor);
  row(pdf, "Return Date", ret, cursor);
  row(pdf, "Duration", application.travel?.duration || (application.travel?.days ? `${application.travel.days} Day(s)` : "-"), cursor);
  cursor.y += 4;
};

const buildPricingSection = (pdf: jsPDF, application: Application, cursor: Cursor) => {
  sectionTitle(pdf, "Insurance Package & Add-ons", cursor);
  const items = application.packages?.length ? application.packages : ["No packages selected"];
  items.forEach((item) => {
    setText(pdf, TEXT_DARK, 10, "normal");
    pdf.text(`•  ${item}`, MARGIN_X, cursor.y);
    cursor.y += 6;
  });

  cursor.y += 2;
  pdf.setDrawColor(LINE_LIGHT[0], LINE_LIGHT[1], LINE_LIGHT[2]);
  pdf.line(MARGIN_X, cursor.y, MARGIN_X + CONTENT_WIDTH, cursor.y);
  cursor.y += 7;

  setText(pdf, BRAND_BLUE, 12, "bold");
  pdf.text("Total Amount", MARGIN_X, cursor.y);
  pdf.text(`RM ${(application.totalPrice ?? 0).toFixed(2)}`, MARGIN_X + CONTENT_WIDTH, cursor.y, { align: "right" });
  cursor.y += 10;
};

const buildFooter = (pdf: jsPDF, application: Application) => {
  const pageHeight = pdf.internal.pageSize.getHeight();
  pdf.setDrawColor(LINE_LIGHT[0], LINE_LIGHT[1], LINE_LIGHT[2]);
  pdf.line(MARGIN_X, pageHeight - 22, MARGIN_X + CONTENT_WIDTH, pageHeight - 22);

  setText(pdf, TEXT_MUTED, 8, "normal");
  pdf.text(
    "This document is auto-generated by ThaiDriveSecure. Keep it accessible during your trip.",
    MARGIN_X,
    pageHeight - 16
  );
  pdf.text(`Reference: ${application.orderId || application.id}`, MARGIN_X, pageHeight - 11);
  pdf.text(
    `Issued: ${format(new Date(), "dd MMM yyyy, HH:mm")}`,
    PAGE_WIDTH - MARGIN_X,
    pageHeight - 11,
    { align: "right" }
  );
};

export const generateInsurancePDF = (application: Application): Blob => {
  const pdf = new jsPDF({ unit: "mm", format: "a4" });
  const cursor: Cursor = { y: 38 };

  buildHeader(pdf, application, cursor);
  buildCustomerSection(pdf, application, cursor);
  buildVehicleSection(pdf, application, cursor);
  buildTravelSection(pdf, application, cursor);
  buildPricingSection(pdf, application, cursor);
  buildFooter(pdf, application);

  return pdf.output("blob");
};
